services:
  app:
    image: client-management-api
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_POSTGRESQL_URL: jdbc:postgresql://postgres:5432/client_manager
      DB_POSTGRESQL_USERNAME: ${DB_POSTGRESQL_USERNAME}
      DB_POSTGRESQL_PASSWORD: ${DB_POSTGRESQL_PASSWORD}

  postgres:
    image: postgres:18
    container_name: client-management-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: client_manager
      POSTGRES_USER: ${DB_POSTGRESQL_USERNAME}
      POSTGRES_PASSWORD: ${DB_POSTGRESQL_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: