spring.application.name=client-management-api

# Database
spring.datasource.url=${DB_POSTGRESQL_URL}
spring.datasource.username=${DB_POSTGRESQL_USERNAME}
spring.datasource.password=${DB_POSTGRESQL_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true